### ISSUE TITLE
Device token validation

### ISSUE THREAD

**Issue by unebutaz** [ZhukV/AppleApnPush#27]
Hi there,
I've got InvalidArgumentException: "Device token must be mask /[^0-9a-f]".
But actually Apple Notification Service correctly proceed even uppercase letters, so this validation part is invalid.

**Comment by ZhukV** [comment]
Thank for you issue.
Fixed.

**Comment by sachinsolanki** [comment]
I found the solution below its working for me.

/vendor/zendframework/zendservice-apple-apns/library/ZendService/Apple/Apns/Message.php
Change from

if (preg_match('/[^0-9a-f]/', $token)) {
throw new Exception\InvalidArgumentException(sprintf(
'Device token must be mask "%s". Token given: "%s"',
'/[^0-9a-f]/',
$token
));
}

TO

if (preg_match('/[^0-9a-fA-F]/', $token)) {
throw new Exception\InvalidArgumentException(sprintf(
'Device token must be mask "%s". Token given: "%s"',
'/[^0-9a-f]/',
$token
));
}
