### ISSUE TITLE
Usage of loc-key & loc-args?

### ISSUE THREAD

**Issue by joanlopez** [ZhukV/AppleApnPush#33]
Hi,

In order to make multilingual Push Notifications, we are used to work with loc-key and loc-args.

How I have to determine this alert parameters with your library?

Thanks! :)

**Comment by ZhukV** [comment]
Hi.

You can use `setBodyLocalize ` in `ApsData` or `setBodyCustom` for inject custom data to APS data.

https://github.com/ZhukV/AppleApnPush/blob/master/src/Notification/ApsData.php#L149

**Comment by joanlopez** [comment]
Hi @ZhukV,

I'm very grateful for you answer, but I'm having problems.

My code is:

```
$aps_data = new ApsData;
$aps_data->setBodyLocalize('my-key', array('param1'));
$message = new Message;
$message->setDeviceToken($device_token); 
$message->setApsData($aps_data);
$notification->send($message);
}
```
The `loc-key` is working and my app is showing the correct text. The problem is that the `loc-args` are not being sent properly. My app is showing `<null>` whereas the same push with another backend code is showing the `loc-args` correctly.

What could be happeing?
How I should use your library? 
Maybe it's a bug of the library?

Many thanks!
