### ISSUE TITLE
Error Code 256 Unpack response error

### ISSUE THREAD

**Issue by ergatech** [ZhukV/AppleApnPush#35]
I am using PHP 5.6 and version 2.2.1 I getting this error on apn 256 - Unpack response error. How can i resolve this problem.

Thans

**Comment by ZhukV** [comment]
Hi. This error exists if certificate file is not valid for your application.
Plese try generate certificate with this manual: http://stackoverflow.com/questions/21250510/generate-pem-file-used-to-setup-apple-push-notification

**Comment by ZhukV** [comment]
@ergatech, your question actually?
