### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by technosailor** [ZhukV/AppleApnPush#38]
Curious if v2 is PHP7 compatible. Unfortunately we're locked in to PHP7 and can't upgrade to 7.1 yet.

**Comment by ZhukV** [comment]
Now, I write code only for PHP 7.1 because we use many returns with nullable hints.

```public function someAction(): ?MyClass```

**Comment by technosailor** [comment]
So does the 2.0 branch support PHP 7.0? I know 3.0 supports only 7.1

**Comment by ZhukV** [comment]
Yes, you can use the 2.0 branch, but the branches 2.* and 3.* have much difference.

Branch 2.0:

PHP >= 5.3.3
Support protocol: binary
Support authentication: Certificate.
Note: you must use feedback service for delete not an active device.

Branch 3.0:

PHP >= 7.1
Support protocol: HTTP 2.0 (If necessary, we can add binary protocol)
Support authentication: Certificate, JWT token (required additional library).

Note: These branches do not have BC for easy upgrade or downgrade version. If you install 2.0, and you want in next time install 3.0, you should refactor your code for work with 3.0

**Comment by ZhukV** [comment]
@technosailor you have any questions about this discussion?
