### ISSUE TITLE
[Feture request] Content Jwt class

### ISSUE THREAD

**Issue by morloderex** [ZhukV/AppleApnPush#39]
Hello @ZhukV 

We are the ability to specify that our certificate is content based. 
But with jwt certificate we only have the ability to specify a specific path.

what if I where to store that file anywhere else than the local file system? 

I am requesting similar ability to the ContentCertificate class here also. :)

**Comment by ZhukV** [comment]
Thank for a feature request. I add this functionality.

**Comment by ZhukV** [comment]
Done. The version of package with this functionality - **v3.0.1**
