### ISSUE TITLE
Add support to keep connections with APNs open across multiple notifications

### ISSUE THREAD

**Issue by andrei-fdsu** [ZhukV/AppleApnPush#58]
I am trying to improve the performance in my project while sending a large number of notifications. So, based on the following topic: Best Practices for Managing Connections on https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW8 it's recommended to keep a single connection alive to send multiple push notifications, as it's my case.

Please, guide me to the way I can do this, if there is any. Or it's possible to include this as an enhancement for this library, as Apple recommended in his Best Practices?

**Comment by ZhukV** [comment]
Hi. We don't close connection after send notification to receiver. And you can send many notifications per one connection (it's supported by HTTP 2.0). For performance and for create application for send many notifications you can create a consumer and listen queues by AMQP (RabbitMQ as an example).
