### ISSUE TITLE
Allow silent, background-notifications

### ISSUE THREAD

**Issue by jhammer** [ZhukV/AppleApnPush#59]
AppleApnPush currently requires that each notification include ‘alert’ as part of the payload. This is problematic because silent, background push notifications are not allowed to include the ‘alert’ key in the payload. See [this page](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification?language=objc) under the `content-available` payload key.

It would be create if AppleApnPush allowed the developer to create a notification that did *not* include an alert. That way we could use it to send silent, background notifications.

Thanks for a great library!

**Comment by ZhukV** [comment]
Interesting! Apple think about developer and many developers wait this functionality ;) But, now I have not more times for apply this changes.

Can you make a Pull Request with this changes?

What must be changed:

* Model `Aps`, set `alert` as optional parameter.
* `PayloadEncoder` and don't encode `alert`, if it empty.

Thank for understand. If you can't make Pull Request, please write here, I add these changes soon.

**Comment by ZhukV** [comment]
Release new version with this feature: `v3.0.8`.
