### ISSUE TITLE
Apple\ApnPush\Protocol\Http\Sender\Exception\HttpSenderException: cURL Error [58]: unable to set private key file

### ISSUE THREAD

**Issue by ashiralibutt** [ZhukV/AppleApnPush#63]
Apple\ApnPush\Protocol\Http\Sender\Exception\HttpSenderException: cURL Error [58]: unable to set private key file: &#039;public/certificate.pem&#039; type PEM in file /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/apple/apn-push/src/Protocol/Http/Sender/CurlHttpSender.php on line 43
Stack trace:
  1. Apple\ApnPush\Protocol\Http\Sender\Exception\HttpSenderException-&gt;() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/apple/apn-push/src/Protocol/Http/Sender/CurlHttpSender.php:43
  2. Apple\ApnPush\Protocol\Http\Sender\CurlHttpSender-&gt;send() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/apple/apn-push/src/Protocol/HttpProtocol.php:135
  3. Apple\ApnPush\Protocol\HttpProtocol-&gt;doSend() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/apple/apn-push/src/Protocol/HttpProtocol.php:91
  4. Apple\ApnPush\Protocol\HttpProtocol-&gt;send() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/apple/apn-push/src/Sender/Sender.php:45
  5. Apple\ApnPush\Sender\Sender-&gt;send() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/app/Http/Controllers/PostController.php:369
  6. App\Http\Controllers\PostController-&gt;sendPushVOIP() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  7. call_user_func_array() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  8. Illuminate\Routing\Controller-&gt;callAction() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
  9. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
 10. Illuminate\Routing\Route-&gt;runController() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176
 11. Illuminate\Routing\Route-&gt;run() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Router.php:680
 12. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 13. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
 14. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 15. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 16. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php:58
 17. Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 18. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 19. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
 20. Illuminate\Pipeline\Pipeline-&gt;then() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682
 21. Illuminate\Routing\Router-&gt;runRouteWithinStack() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Router.php:657
 22. Illuminate\Routing\Router-&gt;runRoute() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Router.php:623
 23. Illuminate\Routing\Router-&gt;dispatchToRoute() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Router.php:612
 24. Illuminate\Routing\Router-&gt;dispatch() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
 25. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 26. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/fideloper/proxy/src/TrustProxies.php:57
 27. Fideloper\Proxy\TrustProxies-&gt;handle() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 28. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 29. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
 30. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 31. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 32. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
 33. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 34. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 35. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
 36. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 37. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 38. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
 39. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 40. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 41. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
 42. Illuminate\Pipeline\Pipeline-&gt;then() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
 43. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
 44. Illuminate\Foundation\Http\Kernel-&gt;handle() /home/wxfmq8yyb5i3/public_html/staging.fluff.notesdb.co/index.php:55

**Comment by ZhukV** [comment]
Please provide absolute path to you certificate or try to use JWT token.
