### ISSUE TITLE
Can't make it work, only the demo

### ISSUE THREAD

**Issue by hiniestic** [ZhukV/AppleApnPush#64]
I can only make vendor/apple/apn-pushdemo/jwt.php work if inside vendor/apple/apn-push I run composer install.
If in a new project I run **composer require apple/apn-push**  and copy the jwt.php code always get:

`PHP Fatal error:  Uncaught Error: Class 'Jose\Component\Core\Converter\StandardConverter' not found in /var/www/html/testPush/vendor/apple/apn-push/src/Jwt/SignatureGenerator/WebTokenJwtSignatureGenerator.php:56
Stack trace:
#0 /var/www/html/testPush/vendor/apple/apn-push/src/Jwt/SignatureGenerator/SignatureGeneratorFactory.php(99): Apple\ApnPush\Jwt\SignatureGenerator\WebTokenJwtSignatureGenerator->__construct()
#1 /var/www/html/testPush/vendor/apple/apn-push/src/Jwt/SignatureGenerator/SignatureGeneratorFactory.php(54): Apple\ApnPush\Jwt\SignatureGenerator\SignatureGeneratorFactory::tryResolveByWebTokenJwtSystem()
#2 /var/www/html/testPush/vendor/apple/apn-push/src/Protocol/Http/Authenticator/JwtAuthenticator.php(71): Apple\ApnPush\Jwt\SignatureGenerator\SignatureGeneratorFactory::resolve()
#3 /var/www/html/testPush/prueba.php(28): Apple\ApnPush\Protocol\Http\Authenticator\JwtAuthenticator->__construct(Object(Apple\ApnPush\Jwt\Jwt))
#4 {main}
  thrown in /var/www/html/testPush/vendor/apple/apn-push/src/Jwt/SignatureGenerator/WebTokenJwtSignatureGenerator.php on line 56

Fatal error: Uncaught Error: Class 'Jose\Component\Core\Converter\StandardConverter' not found in /var/www/html/testPush/vendor/apple/apn-push/src/Jwt/SignatureGenerator/WebTokenJwtSignatureGenerator.php:56
Stack trace:
#0 /var/www/html/testPush/vendor/apple/apn-push/src/Jwt/SignatureGenerator/SignatureGeneratorFactory.php(99): Apple\ApnPush\Jwt\SignatureGenerator\WebTokenJwtSignatureGenerator->__construct()
#1 /var/www/html/testPush/vendor/apple/apn-push/src/Jwt/SignatureGenerator/SignatureGeneratorFactory.php(54): Apple\ApnPush\Jwt\SignatureGenerator\SignatureGeneratorFactory::tryResolveByWebTokenJwtSystem()
#2 /var/www/html/testPush/vendor/apple/apn-push/src/Protocol/Http/Authenticator/JwtAuthenticator.php(71): Apple\ApnPush\Jwt\SignatureGenerator\SignatureGeneratorFactory::resolve()
#3 /var/www/html/testPush/prueba.php(28): Apple\ApnPush\Protocol\Http\Authenticator\JwtAuthenticator->__construct(Object(Apple\ApnPush\Jwt\Jwt))
#4 {main}
  thrown in /var/www/html/testPush/vendor/apple/apn-push/src/Jwt/SignatureGenerator/WebTokenJwtSignatureGenerator.php on line 56`

**Comment by ZhukV** [comment]
Yes, because you don't install required packages for work with JWT token. Please install one of [those packages](https://github.com/ZhukV/AppleApnPush/blob/master/composer.json#L30-L32) for correct test.
