### ISSUE TITLE
JWT authentication refresh token

### ISSUE THREAD

**Issue by Tayfun74** [ZhukV/AppleApnPush#69]
Is there a way to save the current JWT somewhere and use it for at least the next 20 minutes. Apple says the following in their documentation `APNs reports an error if you recreate your tokens more than once every 20 minutes.` (https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns). 

I did not find a way to do this directly, outside of implementing the AuthenticatorInterface and implementing the logic myself.

Any ideas?

**Comment by ZhukV** [comment]
You can create a decorator with use any additional storage (file system, redis, database, etc...) and control update process in it.

**Comment by axeljeremy7** [comment]
@Tayfun74 any update? I am having the same issue

**Comment by ZhukV** [comment]
@Tayfun74 , @axeljeremy7 , if it critical for you, I can add decorator in next days with use `symfony/cache` with implement `psr/cache`. But, your's application support it?

**Comment by Tayfun74** [comment]
@axeljeremy7 I was thinking of implementing a decorator as @ZhukV said, but didn't get time to do it. We are using Symfony @ZhukV so our application would support it, if you got time to add a decorator that would be really nice.

**Comment by axeljeremy7** [comment]
@Tayfun74 @ZhukV  I understand the decorator approach but I dont think i have access to the token so i can stored and I have found a weird or maybe i can be wrong, but when i write like this ```$authenticator = new JwtAuthenticator($jwt, new DateInterval('PT25M'), null);``` , I don’t longer haver errors of to many updates provider tokens, so this seems like a hack, I did debug the debug the code behind and by change the expiration   on ```public function authenticate(Request $request)```, it seems that ```new DateInterval('PT25M')``` does the trick, nevertheless  l would like to know your opinion and if you can try this.

**Comment by ZhukV** [comment]
Added cache functionality in `v3.1.0` release (#70).

```php
use Apple\ApnPush\Jwt\SignatureGenerator\CacheJwtSignatureGenerator;
use Apple\ApnPush\Jwt\SignatureGenerator\SignatureGeneratorFactory;

$tokenGenerator = SignatureGeneratorFactory::resolve();
$cache = new AnyPsr16Cache();
$generator = new CacheJwtSignatureGenerator($tokenGenerator, $cache);

// Third (cache key generator) and fourth (TTL) arguments are optional.
```

**Comment by ZhukV** [comment]
@Tayfun74 , @axeljeremy7 , can you test on your environment?

**Comment by axeljeremy7** [comment]
ok i will test
