### ISSUE TITLE
Alert can be an String

### ISSUE THREAD

**Issue by angelgonzalo** [ZhukV/AppleApnPush#71]
Hi, I have an app using notifications and for whatever reason, it only parse the alert as a string, not a Dictionary, It works and it appear as possible in apple documentation, so I think this library should give an option to send a String type Alert.

This is the apple documentation ( it says "Dictionary (or String)" )
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943363

I have implemented the code to add it, I will send the fork. As the Alert doesn't have fields, I have assumed that the title and the body are parsed in one line separated by a space.

**Comment by ZhukV** [comment]
It possible, but:

1. Apple recommend use alert as object.
2. If we support object and string, we must support in all next releases and all related codes (normalizers/tests/etc...)

If now it easier for development in other projects, we can change signature for methods with alerts and provide easy work with our modes but save previous structure.

As an example:

```php
    /**
     * Set alert
     *
     * @param Alert|string $alert
     *
     * @return Aps
     */
    public function withAlert(Alert|string $alert): Aps
    {
        $cloned = clone $this;

        if (\is_scalar($alert)) {
            $alert = new Alert($alert);
        }

        $cloned->alert = $alert;

        return $cloned;
    }
```

As result for development you can easy change alert (`$aps->withAlert('Foo Bar')`), and we save full previous structure.

@angelgonzalo , you have a some problem with create alert and want to add possible add alert as string?

**Comment by angelgonzalo** [comment]
Hi,

this doesn't work, the problem is while doing the json encodig. You only have a method convertAlertToArray an I need one to do create a string alert. But I also have a problem with custom data. Te app is specting it to be inside aps so I have to modify another part of the library too, so I need to keep a separate fork until the app parse it properly.

Thanks for your help and good job!
