### ISSUE TITLE
Support Certificate p12

### ISSUE THREAD

**Issue by h-o-sein** [ZhukV/AppleApnPush#72]
Does it support Certificate p12?

**Comment by ZhukV** [comment]
Yes, we full support use certificates over HTTP layer. Please see demo: https://github.com/ZhukV/AppleApnPush/blob/master/demo/certificate.php

**Comment by ZhukV** [comment]
But you should convert you `*.p12` certificates to `*.pem` certificate. You can read docs here: https://stackoverflow.com/questions/21250510/generate-pem-file-used-to-set-up-apple-push-notifications
