### ISSUE TITLE
Add support for `url-args` for macOS Safari web push

### ISSUE THREAD

**Issue by rjmahieu** [ZhukV/AppleApnPush#74]
When sending web push to Safari in macOS, APNs expects the property `url-args` to be present in the `aps` body, even if it's just an empty array.

If it's not included, the following error will be triggered:

`["Failed to parse remote notification payload: payload must contain a \"url-args\" array inside the \"aps\" dictionary"]`

Relevant section in Apple's documentation:

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW12

**Comment by rjmahieu** [comment]
I'm picking up this fix myself, will create the pull request once ready.

**Comment by ZhukV** [comment]
Thank you for contributing. The version `v3.1.2` contain this functionality.
